export enum Screens {
  BOTTOM = 'BOTTOM',

  //MAIN
  HOME = 'HOME',
  SEARCH = 'SEARCH',
  VIDEO = 'VIDEO',
  NOTIFICATION = 'NOTIFICATION',
  PROFILE = 'PROFILE',

  //AUTH
  AUTH = 'AUTH',
  REGISTRATION = 'REGISTRATION',
}
